#!/bin/bash

camera=$1
center="192.168.8.119/axis-cgi/com/ptz.cgi?pan=0&tilt=0&zoom=0"
machine1="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-10&tilt=16&zoom=1300"
machine2="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-10&tilt=0&zoom=1600"
machine3="192.168.8.119/axis-cgi/com/ptz.cgi?pan=3&tilt=18&zoom=1700"
machine4="192.168.8.119/axis-cgi/com/ptz.cgi?pan=3&tilt=4&zoom=1650"
machine5="192.168.8.119/axis-cgi/com/ptz.cgi?pan=9&tilt=12&zoom=30"
you="192.168.8.119/axis-cgi/com/ptz.cgi?pan=180&tilt=0&zoom=0"
case $camera in
    machine-1)
        curl $machine1
        echo Watching feed $camera.
        ;;
    machine-2)
        curl $machine2
        echo Watching feed $camera.
        ;;
    machine-3)
        curl $machine3
        echo Watching feed $camera.
        ;;
    machine-4)
        curl $machine4
        echo Watching feed $camera.
        ;;
    machine-5)
        curl $machine5
        echo Watching feed $camera.
        ;;
    you)
        curl $you
        echo Watching $camera.
        ;;
    loop)
        echo Starting loop.
        curl $center
        sleep 5s
        curl $machine1
        sleep 5s
        curl $machine2
        sleep 5s
        curl $machine3
        sleep 5s
        curl $machine4
        sleep 5s
        curl $machine5
        sleep 5s
        curl $you
        sleep 5s
        curl $machine5
        ;;

    *)
        curl $center
        echo Watching all.
        ;;
esac
