#!/bin/bash

camera=$1

feed0="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-10&tilt=8&zoom=0"
feed1="192.168.8.119/axis-cgi/com/ptz.cgi?pan=1&tilt=0&zoom=700"
feed2="192.168.8.119/axis-cgi/com/ptz.cgi?pan=0&tilt=11&zoom=1200"
feed3="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-15&tilt=13&zoom=1000"
feed4="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-10&tilt=0&zoom=800"
feed5="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-20&tilt=0&zoom=1000"

you="192.168.8.119/axis-cgi/com/ptz.cgi?pan=180&tilt=0&zoom=0"

case $camera in
    machine-1)
        curl $feed1
        echo Watching feed $camera.
        ;;
    machine-2)
        curl $feed2
        echo Watching feed $camera.
        ;;
    machine-3)
        curl $feed3
        echo Watching feed $camera.
        ;;
    machine-4)
        curl $feed4
        echo Watching feed $camera.
        ;;
    machine-5)
        curl $feed5
        echo Watching feed $camera.
        ;;
    you)
        curl $you
        echo Watching $camera.
        ;;
    loop)
        echo Starting loop.
        curl $feed0
        sleep 1s
        curl $feed1
        sleep 1s
        curl $feed2
        sleep 1s
        curl $feed3
        sleep 1s
        curl $feed4
        sleep 1s
        curl $feed5
        sleep 1s
        curl $feed0
        sleep 3s
        curl $you
        sleep 5s
        curl $feed0
        ;;

    *)
        curl $feed0
        echo Watching all.
        ;;
esac
