#!/bin/bash

machine=$1
machine1=192.168.8.228
machine2=192.168.8.170
machine3=192.168.8.169
machine4=192.168.8.155
machine5=192.168.8.191

number=${2:-1}
pausetime=${3:-1}

feed0="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-10&tilt=10&zoom=0" 
feed1="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-15&tilt=13&zoom=1000" 
feed2="192.168.8.119/axis-cgi/com/ptz.cgi?pan=0&tilt=11&zoom=1200" 
feed3="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-20&tilt=0&zoom=1000" 
feed4="192.168.8.119/axis-cgi/com/ptz.cgi?pan=-10&tilt=0&zoom=800" 
feed5="192.168.8.119/axis-cgi/com/ptz.cgi?pan=1&tilt=0&zoom=700" 

case $machine in
    machine-1)
        for i in $(seq "$number")
        do
            echo "Hello, $machine." | nc -cu $machine1 10000
            echo -e "Ping \e[91mMachine 1 \e[39m$i times."
            sleep $pausetime
        done
        ;;
    machine-2)
        for i in $(seq "$number")
        do
            echo "Hello, $machine." | nc -cu $machine2 10000
            echo -e "Ping \e[91mMachine 2 \e[39m$i times."
            sleep $pausetime
        done
        ;;
    machine-3)
        for i in $(seq "$number")
        do
            echo "Hello, $machine." | nc -cu $machine3 10000
            echo -e "Ping \e[91mMachine 3 \e[39m$i times."
            sleep $pausetime
        done
        ;;
    machine-4)
        for i in $(seq "$number")
        do
            echo "Hello, $machine." | nc -cu $machine4 10000
            echo -e "Ping \e[91mMachine 4 \e[39m$i times."
            sleep $pausetime
        done
        ;;
    machine-5)
        for i in $(seq "$number")
        do
            echo "Hello, $machine." | nc -cu $machine5 10000
            echo -e "Ping \e[91mMachine 5 \e[39m$i times."
            sleep $pausetime
        done
        ;;
    cycle)
        for i in $(seq "$number")
        do
            echo "Hello, $machine." | nc -cu $machine1 10000
            echo -e "Ping \e[91mMachine 5 \e[39m$i times."
            sleep $pausetime

            echo "Hello, $machine." | nc -cu $machine2 10000
            echo -e "Ping \e[91mMachine 5 \e[39m$i times."
            sleep $pausetime

            echo "Hello, $machine." | nc -cu $machine3 10000
            echo -e "Ping \e[91mMachine 5 \e[39m$i times."
            sleep $pausetime

            echo "Hello, $machine." | nc -cu $machine4 10000
            echo -e "Ping \e[91mMachine 5 \e[39m$i times."
            sleep $pausetime

            echo "Hello, $machine." | nc -cu $machine5 10000
            echo -e "Ping \e[91mMachine 5 \e[39m$i times."
            sleep $pausetime
        done
        ;;
    *)
        for i in $(seq "$number")
        do
            echo "Hello, world." | nc -cu $machine1 10000
            echo "Hello, world." | nc -cu $machine2 10000
            echo "Hello, world." | nc -cu $machine3 10000
            echo "Hello, world." | nc -cu $machine4 10000
            echo "Hello, world." | nc -cu $machine5 10000
            echo -e "\e[91mBroadcast network $i times."
            sleep $pausetime
        done
        ;;
esac
